version: "3.6"

services:
  sut:
    build: .
    volumes:
      - qbittorrent_config:/config
    command: >
      bash -c "/usr/bin/qbittorrent-nox --webui-port=8111 &
               /usr/local/bin/test.sh -t 30 -u http://localhost:8112/ -e qBittorrent"

volumes:
  qbittorrent_config:
    driver_opts:
      type: tmpfs
      device: tmpfs
